### ISSUE TITLE
共存无法保存登入状态

### ISSUE THREAD

**Issue by afaa1991** [zetaloop/BetterWX#2]
非常好用，感谢大佬无私开源。现在有个问题就是4.0.1版本的微信不能保存登入状态。登入状态应该还和 net 文件夹有关，期待大佬修复。

**Comment by zetaloop** [comment]
可以描述一下，现在具体是怎么个现象吗？

**Comment by afaa1991** [comment]
共存的第二个微信登入后，打开登入第一个微信虽有显示头像，但是点击后需要重新扫码登入，理想的状态应该是每个微信都可以直接点击登入，这样就不用每次都扫码了。
用备份的net文件夹还原后，可以直接点击登入对应微信，不会跳转扫码，所以 因该还需要处理 net 文件夹。
位置是：C:\Users\用户名\AppData\Roaming\Tencent\xwechat\net 这个文件夹

**Comment by afaa1991** [comment]
共存的第二个微信登入后，打开登入第一个微信虽有显示头像，但是点击后需要重新扫码登入，理想的状态应该是每个微信都可以直接点击登入，这样就不用每次都扫码了。
用备份的net文件夹还原后，可以直接点击登入对应微信，不会跳转扫码，所以 因该还需要处理 net 文件夹。
位置是：C:\Users\用户名\AppData\Roaming\Tencent\xwechat\net 这个文件夹

**Comment by zetaloop** [comment]
根源位于 xwechat\net\host\host-redirect.xml。
这里似乎存的是登录端口地址？不清楚为什么这个配置不一致会导致自动登录失败...

我试试给共存版单独设定这个文件的路径。

**Comment by zetaloop** [comment]
你看看如果手动恢复 host-redirect.xml，能够自动登录各个账号吗

**Comment by zetaloop** [comment]
已更新 coexist.py。
经测试，原版和共存版均能自动登录了。
你试试？

**Comment by afaa1991** [comment]
可以，大佬威武
