### ISSUE TITLE
共存版卡在这里不会动啊，没有生成

### ISSUE THREAD

**Issue by popokcn** [zetaloop/BetterWX#3]
![PixPin_2024-12-24_18-12-33](https://github.com/user-attachments/assets/6b193632-5155-43a3-a889-57222c23381e)

python版本Python 3.13.1，刚下载的。

微信也是刚下载的，版本4.0.19，是不是19版本还没适配

**Comment by zetaloop** [comment]
可以描述一下你是怎样操作的吗？例如你点开脚本之后，输入了 1，换行，输入了 z？
注意 Weixin.exe 这里需要填入微信可执行文件的路径，例如 `D:\Program Files\Tencent\WeChat\Weixin.exe`。

此外，测试版最新版好像是 4.0.1.17，你的版本号确定是 4.0.19 吗？可以把关于页截个图看看吗？

**Comment by popokcn** [comment]
[image: PixPin_2024-12-24_18-25-33.png]

输入数字后回车，显示Weixin.exe，然后卡着不动，我以为后台已近在生成了呢。原来这里还需要输入weixin.exe的路径啊，我再去试试


zetaloop ***@***.***> 于2024年12月24日周二 18:23写道：

**Comment by popokcn** [comment]
好像可以了，哈哈哈，我去试试看，这19版本的修补后能不能正常使用。
[image: PixPin_2024-12-24_18-27-45.png]

popok ***@***.***> 于2024年12月24日周二 18:26写道：

**Comment by popokcn** [comment]
[image: image.png]

测试了一下，多开没有问题

popok ***@***.***> 于2024年12月24日周二 18:28写道：

**Comment by zetaloop** [comment]
对了，如果要让本体 Weixin.exe 和多开版 Weixin1.exe... 一起使用，本体也需要打一下多开补丁（unlock.py）
